spring:
  redis:
    database: 0
    jedis:
      pool:
        max-active: 300
        max-idle: 100
        max-wait: -1
        min-idle: 20
    sentinel:
      master: mymaster
      nodes: localhost:26381,localhost:26382,localhost:26383
    port: 6381
    password:
    host: localhost
  redis-write:
    host: localhost
    port: 6381
    password:
    testOnBorrow: false
  redis-read:
    host: localhost
    port: 6382
    password:
    testOnBorrow: false

server:
  port: 8081


